package com.wangqiang.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.wangqiang.greendao.LessonInfo;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "LessonCache".
*/
public class LessonInfoDao extends AbstractDao<LessonInfo, Long> {

    public static final String TABLENAME = "LessonCache";

    /**
     * Properties of entity LessonInfo.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property UnitNo = new Property(1, String.class, "UnitNo", false, "UNIT_NO");
        public final static Property LessonNo = new Property(2, String.class, "LessonNo", false, "LESSON_NO");
        public final static Property Content = new Property(3, String.class, "content", false, "CONTENT");
        public final static Property Title = new Property(4, String.class, "title", false, "TITLE");
        public final static Property Meaning = new Property(5, String.class, "meaning", false, "MEANING");
    };


    public LessonInfoDao(DaoConfig config) {
        super(config);
    }
    
    public LessonInfoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"LessonCache\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"UNIT_NO\" TEXT NOT NULL ," + // 1: UnitNo
                "\"LESSON_NO\" TEXT NOT NULL ," + // 2: LessonNo
                "\"CONTENT\" TEXT NOT NULL ," + // 3: content
                "\"TITLE\" TEXT NOT NULL ," + // 4: title
                "\"MEANING\" TEXT NOT NULL );"); // 5: meaning
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"LessonCache\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, LessonInfo entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getUnitNo());
        stmt.bindString(3, entity.getLessonNo());
        stmt.bindString(4, entity.getContent());
        stmt.bindString(5, entity.getTitle());
        stmt.bindString(6, entity.getMeaning());
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public LessonInfo readEntity(Cursor cursor, int offset) {
        LessonInfo entity = new LessonInfo( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // UnitNo
            cursor.getString(offset + 2), // LessonNo
            cursor.getString(offset + 3), // content
            cursor.getString(offset + 4), // title
            cursor.getString(offset + 5) // meaning
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, LessonInfo entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setUnitNo(cursor.getString(offset + 1));
        entity.setLessonNo(cursor.getString(offset + 2));
        entity.setContent(cursor.getString(offset + 3));
        entity.setTitle(cursor.getString(offset + 4));
        entity.setMeaning(cursor.getString(offset + 5));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(LessonInfo entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(LessonInfo entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
