package com.wangqiang.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.wangqiang.greendao.WordInfo;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "WordCache".
*/
public class WordInfoDao extends AbstractDao<WordInfo, Long> {

    public static final String TABLENAME = "WordCache";

    /**
     * Properties of entity WordInfo.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property LessonNo = new Property(1, String.class, "lessonNo", false, "LESSON_NO");
        public final static Property Content = new Property(2, String.class, "content", false, "CONTENT");
        public final static Property Level = new Property(3, String.class, "level", false, "LEVEL");
        public final static Property Meaning = new Property(4, String.class, "meaning", false, "MEANING");
    };


    public WordInfoDao(DaoConfig config) {
        super(config);
    }
    
    public WordInfoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"WordCache\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"LESSON_NO\" TEXT NOT NULL ," + // 1: lessonNo
                "\"CONTENT\" TEXT NOT NULL ," + // 2: content
                "\"LEVEL\" TEXT NOT NULL ," + // 3: level
                "\"MEANING\" TEXT NOT NULL );"); // 4: meaning
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"WordCache\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, WordInfo entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getLessonNo());
        stmt.bindString(3, entity.getContent());
        stmt.bindString(4, entity.getLevel());
        stmt.bindString(5, entity.getMeaning());
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public WordInfo readEntity(Cursor cursor, int offset) {
        WordInfo entity = new WordInfo( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // lessonNo
            cursor.getString(offset + 2), // content
            cursor.getString(offset + 3), // level
            cursor.getString(offset + 4) // meaning
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, WordInfo entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setLessonNo(cursor.getString(offset + 1));
        entity.setContent(cursor.getString(offset + 2));
        entity.setLevel(cursor.getString(offset + 3));
        entity.setMeaning(cursor.getString(offset + 4));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(WordInfo entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(WordInfo entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
